services:
  db:
    image: postgres:16-alpine
    container_name: conciwedding_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=conci
      - POSTGRES_PASSWORD=conci
      - POSTGRES_DB=conciwedding
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: conciwedding_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
